// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skoacddbuyyxvqbbtywj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrb2FjZGRidXl5eHZxYmJ0eXdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNTM4MDcsImV4cCI6MjA3MDgyOTgwN30.cq1XYAtelTvvMWpEfvGXS5ByanWU3M3D8FQjLEtqKtY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});